#!/bin/env bash
flutter clean
./clear_app_data
# See https://github.com/flutter/flutter/issues/58247#issuecomment-636500680
flutter build apk --debug
flutter build apk --profile
flutter run --release
